 --IT부서에서 근무하고 있는 사람들을 출력하라 DEPARTMENT, EMPLOYEE
 SELECT D.DEPARTMENT_NAME, E.FIRST_NAME|| ' '|| E.LAST_NAME AS NAME FROM EMPLOYEES E, DEPARTMENTS D
 WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND d.department_name = 'IT';
 
 
 DROP TABLE EMP;
 DROP TABLE DEPT;
 
 ALTER TABLE EMP ADD CONSTRAINT FK_DEPT_TO_EMP FOREIGN KEY(DEPT_NO) REFERENCES DEPT(DEPT_NO);