
-- COMMENT
-- ALTER ADD / RENAME / MODIFY / DROP
-- UPDATE(데이터 수정) / DELETE 
    -- WHERE - AND - OR
        UPDATE CONTACT SET LAST_NAME = '수아' WHERE CONTACT_NO = 2;  
        UPDATE CONTACT SET LAST_NAME = '진상' WHERE CONTACT_NO = 2 OR contact_no = 4;  
    DELETE FROM CONTACT WHERE CONTACT_NO = 5;
    
-- SELECT+ORDER ASC, DESC (오름차순, 내림차순 정리)
    SELECT * FROM GIFT ORDER BY NAME ASC;
    SELECT * FROM GIFT ORDER BY NAME DESC;
    
--SELECT + 그룹핑
  SELECT * FROM GIFT; 
  SELECT PRICE FROM GIFT GROUP BY PRICE;
  SELECT PRICE AS MONEY FROM GIFT GROUP BY PRICE; -- AS MONEY 붙여서 별명
  SELECT TYPE AS YPTE, SUM(PRICE) AS GOODS FROM GIFT GROUP BY TYPE;
  SELECT TYPE AS GOODS, COUNT(TYPE) AS COU, SUM(PRICE) AS GOOD FROM GIFT GROUP BY TYPE;

-- SELECT+WHERE
  SELECT * FROM GIFT WHERE NO>3;
  SELECT * FROM GIFT WHERE NO<5;
  SELECT * FROM GIFT WHERE PRICE > 100000;
  SELECT * FROM GIFT WHERE PRICE > 100000 AND PRICE < 500000;
  SELECT*FROM GIFT WHERE NOT PRICE < 50000;
  SELECT NO+PRICE FROM GIFT WHERE NO = 3;
  SELECT '두개의 값 : ' ||(NO+PRICE)|| '이라함.' AS RESULT FROM GIFT WHERE NO = 3;
  -- 두개의 값을 같이 표현하고 싶을 때는 '( )' 안에 있는걸로 해줘야 함.
  
  -- BETWEEN, IN
  SELECT * FROM GIFT WHERE PRICE BETWEEN 50000 AND 600000; -- ~사이의 범위 지정
  SELECT * FROM GIFT WHERE PRICE NOT BETWEEN 50000 AND 600000;
  SELECT * FROM GIFT WHERE PRICE IN (10000, 30000, 50000, 90000); -- 정확한 값의 범위 지정
  
  SELECT * FROM GIFT WHERE PRICE NOT IN (10000, 30000, 50000, 90000);
  
  SELECT *, CHK FROM GIFT WHERE PRICE NOT IN (10000, 30000, 50000, 90000)(SELECT TYPE FROM GIFT AS CHK WHERE TYPE LIKE ('%제품%'));
  
  
  -- LIKE
  SELECT * FROM GIFT WHERE TYPE LIKE('%제품%');
  SELECT * FROM CONTACT WHERE PHONE LIKE('%3171%');
  
  -- 함수
--CHR
     SELECT CHR(65) FROM DUAL;
     SELECT CHR(99) FROM DUAL;
--LOWER
    SELECT LOWER('ABCDEFG') FROM DUAL;
--UPPER
    SELECT UPPER('abcdefg') FROM DUAL;
--LTRIM, TRIM, RTRIM
    SELECT LTRIM('       AAAA') FROM DUAL;
    SELECT LTRIM('BBBBAAAA','BBBB') FROM DUAL;
    SELECT RTRIM('AAAA       ') FROM DUAL;
    SELECT RTRIM('AAAABBBB', 'BBBB') FROM DUAL;
    SELECT TRIM ('     AAAAA       ') FROM DUAL;
    SELECT TRIM (LEADING 'A' FROM 'ABBBBBBBBB') FROM DUAL;
    SELECT TRIM (TRAILING 'A' FROM 'BBBBBBBBBA') FROM DUAL;
    SELECT TRIM (BOTH 'A' FROM 'AABBBBBBBBBBBBAA') FROM DUAL;
--SUBSTR
    SELECT SUBSTR ('ABCDEFGHIJK',3,5)FROM DUAL;
    SELECT SUBSTR ('ANCDEFGHIJK',5) FROM DUAL;
--LENGTH
    SELECT LENGTH('ABCEDFGHIJK') FROM DUAL;
    SELECT LENGTH('가나다라마바사') FROM DUAL;
 --REPLACE
    SELECT REPLACE('ABCDEFGHIJK', 'FGHIJK') FROM DUAL;
    SELECT REPLACE('ABCDEFGHIJK', 'FGHIJK', '가나다라마') FROM DUAL;
    
    